//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> LastPurchase { get; set; }
        public System.Guid SellerId { get; set; }
        public Nullable<System.Guid> RegionId { get; set; }
        public Nullable<System.Guid> ClassificationId { get; set; }
        public System.Guid ClientId { get; set; }
        public string Address { get; set; }
        public string Occupation { get; set; }
    }
}
